### ISSUE TITLE
How to connect to FitBit web api with FitBit Charge 3?

### ISSUE THREAD

**Issue by tonnoz** [CaseDelst/FitByte#1]
Hello from what I see from the website only FitBit Versa, Versa-lite and Ionic are recognized. How did you manage to connect the Charge 3? 
Thanks!

**Comment by cdelst** [comment]
Hello, thanks for the issue.  

As far as I know, the system works like this: 

The data is stored in the FitBit, and then when synced to the phone, it is sent to FitBit's server.  At that point I do not think there is any difference when gathering the data, other than obvious things like some devices may not have a heart rate sensor.  You should not have to do anything special to get data from your Charge 3, as that is what I have.  

Thanks!
Case

**Comment by tonnoz** [comment]
Hello Thanks! Ill close the issue!
